# Generated by Django 2.1b1 on 2018-07-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=256)),
                ('cdesc', models.CharField(blank=True, max_length=256, null=True)),
                ('cid', models.IntegerField()),
                ('promotion', models.CharField(blank=True, max_length=1000, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ITEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=256)),
                ('itemid', models.IntegerField()),
                ('subcatid', models.IntegerField()),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CATEGORY')),
            ],
        ),
        migrations.CreateModel(
            name='SHOPtab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=256)),
                ('saddress', models.CharField(blank=True, max_length=256, null=True)),
                ('longi', models.CharField(blank=True, max_length=256, null=True)),
                ('lati', models.CharField(blank=True, max_length=1000, null=True)),
                ('NTN', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(max_length=1000)),
                ('desc', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SUBCAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('subcatid', models.IntegerField()),
                ('promotion', models.CharField(blank=True, max_length=1000, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('parentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.CATEGORY')),
                ('subparentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SUBCAT')),
            ],
        ),
    ]
