# Generated by Django 2.1b1 on 2018-07-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180708_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='subcategory_name',
            field=models.CharField(max_length=256),
        ),
    ]
