# Generated by Django 2.1b1 on 2018-07-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180708_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subcat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.SUBCAT'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
