# Generated by Django 2.1b1 on 2018-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180708_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_tag',
            field=models.CharField(max_length=256),
        ),
    ]
