# Generated by Django 2.1b1 on 2018-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180708_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_rating',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_unit',
            field=models.CharField(max_length=16),
        ),
    ]
