# Generated by Django 2.1b1 on 2018-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180708_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
